// Code generated by protoc-gen-go.
// source: field.proto
// DO NOT EDIT!

/*
Package cell is a generated protocol buffer package.

It is generated from these files:
	field.proto

It has these top-level messages:
	FieldProto
*/
package cell

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// FieldProto represents the entire state of a 2D cellular automaton.
type FieldProto struct {
	// State holds the state information. The state for the cell at (x, y)
	// is stored at State[Width * y + x].
	State []uint32 `protobuf:"varint,1,rep,name=state" json:"state,omitempty"`
	// Width is one dimension of the 2D state. The state is of size Width
	// times Height.
	Width int32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	// Height is one dimension of the 2D state. The state is of size Width
	// times Height.
	Height int32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
}

func (m *FieldProto) Reset()         { *m = FieldProto{} }
func (m *FieldProto) String() string { return proto.CompactTextString(m) }
func (*FieldProto) ProtoMessage()    {}
