// Code generated by protoc-gen-go.
// source: input.proto
// DO NOT EDIT!

/*
Package cell is a generated protocol buffer package.

It is generated from these files:
	input.proto

It has these top-level messages:
	UpdateRequest
	UpdateResponse
	UpdateMaskRequest
	ResetFieldRequest
*/
package cell

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// UpdateRequest is used to to modify a running Game of Life simulation.
type UpdateRequest struct {
	// Types that are valid to be assigned to Input:
	//	*UpdateRequest_UpdateMask
	//	*UpdateRequest_ResetField
	Input isUpdateRequest_Input `protobuf_oneof:"input"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}

type isUpdateRequest_Input interface {
	isUpdateRequest_Input()
}

type UpdateRequest_UpdateMask struct {
	UpdateMask *UpdateMaskRequest `protobuf:"bytes,1,opt,name=update_mask,oneof"`
}
type UpdateRequest_ResetField struct {
	ResetField *ResetFieldRequest `protobuf:"bytes,2,opt,name=reset_field,oneof"`
}

func (*UpdateRequest_UpdateMask) isUpdateRequest_Input() {}
func (*UpdateRequest_ResetField) isUpdateRequest_Input() {}

func (m *UpdateRequest) GetInput() isUpdateRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *UpdateRequest) GetUpdateMask() *UpdateMaskRequest {
	if x, ok := m.GetInput().(*UpdateRequest_UpdateMask); ok {
		return x.UpdateMask
	}
	return nil
}

func (m *UpdateRequest) GetResetField() *ResetFieldRequest {
	if x, ok := m.GetInput().(*UpdateRequest_ResetField); ok {
		return x.ResetField
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), []interface{}) {
	return _UpdateRequest_OneofMarshaler, _UpdateRequest_OneofUnmarshaler, []interface{}{
		(*UpdateRequest_UpdateMask)(nil),
		(*UpdateRequest_ResetField)(nil),
	}
}

func _UpdateRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateRequest)
	// input
	switch x := m.Input.(type) {
	case *UpdateRequest_UpdateMask:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.UpdateMask); err != nil {
			return err
		}
	case *UpdateRequest_ResetField:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ResetField); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("UpdateRequest.Input has unexpected type %T", x)
	}
	return nil
}

func _UpdateRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateRequest)
	switch tag {
	case 1: // input.update_mask
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(UpdateMaskRequest)
		err := b.DecodeMessage(msg)
		m.Input = &UpdateRequest_UpdateMask{msg}
		return true, err
	case 2: // input.reset_field
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResetFieldRequest)
		err := b.DecodeMessage(msg)
		m.Input = &UpdateRequest_ResetField{msg}
		return true, err
	default:
		return false, nil
	}
}

// UpdateResponse is the response to an UpdateRequest.
//
// It is blank for now, but exists in case we need to add response information
// in the future.
type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}

// UpdateMaskRequest modifies the mask used in the Game of Life calculation.
//
// The default mask is used to filter the calculations to use every three
// bits for the game of life.
type UpdateMaskRequest struct {
	Value uint32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *UpdateMaskRequest) Reset()         { *m = UpdateMaskRequest{} }
func (m *UpdateMaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMaskRequest) ProtoMessage()    {}

// ResetFieldRequest modifies the field to be a random state.
type ResetFieldRequest struct {
}

func (m *ResetFieldRequest) Reset()         { *m = ResetFieldRequest{} }
func (m *ResetFieldRequest) String() string { return proto.CompactTextString(m) }
func (*ResetFieldRequest) ProtoMessage()    {}
