FROM gcr.io/golang-game-of-life/goczmq

# Install Go package dependencies.
RUN go get github.com/bradfitz/iter
RUN go get github.com/golang/protobuf/proto
RUN go get github.com/zeromq/goczmq

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/tswast/gameoflife


# Build the gameoflife command.
RUN go install github.com/tswast/gameoflife/pub

# Run the Game of Life publisher command by default when the container starts.
ENTRYPOINT /go/bin/pub

EXPOSE 5000
EXPOSE 5001
